"""Offline threshold selection. Only explicit human-positive/negative labels are evaluated.
Calibration and validation IDs/authors must be disjoint; unknown labels are never negatives.
Scores are generated by ai-probe --score-list through the product Rust input path.
"""
import argparse, json, math, pathlib
CLASSES = ('person', 'bird', 'car', 'mountain', 'sea', 'forest', 'night')

def metrics(pairs, threshold):
    tp = sum(label == 1 and score >= threshold for label, score in pairs)
    fp = sum(label == 0 and score >= threshold for label, score in pairs)
    fn = sum(label == 1 and score < threshold for label, score in pairs)
    positives = sum(label == 1 for label, _ in pairs)
    negatives = len(pairs) - positives
    return dict(tp=tp, fp=fp, fn=fn, positives=positives, negatives=negatives,
                precision=tp/(tp+fp) if tp+fp else None, recall=tp/positives if positives else None)

def select(pairs, precision_target=.9, beta=None, min_tp=1):
    # Largest recall among thresholds meeting precision on calibration only.
    candidates = [value for _, value in pairs]
    qualified = [(metrics(pairs, t), t) for t in set(candidates)]
    qualified = [(m, t) for m, t in qualified if m['precision'] is not None and m['precision'] >= precision_target and m['tp'] >= min_tp]
    if not 0 < precision_target <= 1 or min_tp < 1 or beta is not None and (not math.isfinite(beta) or beta <= 0):
        raise ValueError('invalid calibration policy')
    def rank(item):
        m, t = item
        p, r = m['precision'], m['recall']
        value = r if beta is None else (1 + beta**2) * p * r / (beta**2 * p + r)
        return value, p, t
    return max(qualified, key=rank)[1] if qualified else None

def analyze(samples, scores, precision_target=.9, beta=None, min_tp=1):
    usable = [r for r in samples if 'path' in r and r['id'] in scores and 'error' not in scores[r['id']]]
    groups = {}
    ids = set()
    for row in usable:
        if row['id'] in ids: raise ValueError('duplicate sample ID')
        ids.add(row['id'])
        group = row.get('author_profile') or row.get('author') or row['sha256']
        if group in groups and groups[group] != row['split']: raise ValueError('photographer appears in both splits')
        groups[group] = row['split']
    output = {}
    for policy in ('CenterCrop', 'Fit'):
        classes = {}
        for name in CLASSES:
            pairs = {part: [] for part in ('calibration', 'validation')}
            for row in usable:
                value = row['labels'].get(name)
                if value is None: continue
                if value not in (0, 1): raise ValueError('label must be explicit 0 or 1')
                score = scores[row['id']]['scores'][policy][name]
                if not math.isfinite(score) or not -1 <= score <= 1: raise ValueError('invalid cosine score')
                pairs[row['split']].append((value, score))
            threshold = select(pairs['calibration'], precision_target, beta, min_tp)
            if threshold is None:
                classes[name] = dict(threshold=None, passed=False, reason='no non-empty calibration result meets precision target')
                continue
            train = metrics(pairs['calibration'], threshold)
            test = metrics(pairs['validation'], threshold)
            enough = test['positives'] >= 30 and test['negatives'] >= 50
            passed = enough and test['precision'] is not None and test['precision'] >= .9 and test['recall'] >= .6
            errors = [dict(id=r['id'], expected=r['labels'][name], score=scores[r['id']]['scores'][policy][name]) for r in usable
                      if r['split']=='validation' and name in r['labels'] and ((scores[r['id']]['scores'][policy][name] >= threshold) != bool(r['labels'][name]))]
            classes[name] = dict(threshold=threshold, calibration=train, validation=test, enough_support=enough, passed=passed, errors=errors[:20])
        output[policy] = dict(classes=classes, quality_validated=all(r['passed'] for r in classes.values()))
    return dict(samples=len(samples), usable=len(usable), excluded=len(samples)-len(usable),
                split_counts={s:sum(r['split']==s for r in usable) for s in ('calibration','validation')},
                split_group='photographer', policies=output,
                limitations=['Open Images labels describe its concepts, not RayBend acceptance on real libraries.',
                             'Unlabeled classes remain unknown; this is a selected cohort, not a natural class prevalence estimate.',
                             'No guarantee against near duplicates across different photographers.'])

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--manifest',type=pathlib.Path,required=True)
    parser.add_argument('--scores',type=pathlib.Path,nargs='+',required=True);parser.add_argument('--output',type=pathlib.Path,required=True)
    parser.add_argument('--precision-target',type=float,default=.9);parser.add_argument('--beta',type=float);parser.add_argument('--min-tp',type=int,default=1)
    args=parser.parse_args();scores={}
    for file in args.scores:
        for line in file.read_text().splitlines():
            row=json.loads(line)
            if 'id' in row:
                if row['id'] in scores: raise ValueError('duplicate inference result')
                scores[row['id']]=row
    report=analyze(json.loads(args.manifest.read_text()),scores,args.precision_target,args.beta,args.min_tp);
    if args.beta is not None or args.precision_target != .9 or args.min_tp != 1:
        report['threshold_policy'] = dict(precision_target=args.precision_target,beta=args.beta,min_tp=args.min_tp,selected_on='calibration only',strict_previous_gate_retained=True)
    args.output.write_text(json.dumps(report,ensure_ascii=False,indent=2))
    print(json.dumps({policy:{name: {k:v for k,v in row.items() if k not in ('errors','calibration')} for name,row in value['classes'].items()} for policy,value in report['policies'].items()},indent=2))
if __name__=='__main__':main()
